### ISSUE TITLE
Add support for symbolic links

### ISSUE THREAD

**Issue by kelson42** [openzim/zimwriterfs#9]
_From @julianharty on May 8, 2017 20:25_

Here's what I know, the bug may be more general or very specific to my case. More testing could help identify the extent, for instance to see if the same behavior happens when using soft-links for images, html, etc.

# Ingredients:

* zimwriterfs (I used the current Docker Image that contains it). Note I added a shared folder so I could easily share data between the running Docker image and my macbook. This had to be configured using the command line. See https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine for tips on how to do this.
* some basic content. I generated it from the https://github.com/julianharty/testing-heuristics project (follow the instructions in the README)
* create a folder called `./A` in the `dist` folder
* create a soft-link using `ln -s` for style.css: `ln -s style.css A/style.css`
* run zimwriterfs with the following command (in the extract below) in the running Docker container.

Using a soft-link (`ln -s source-file destination-file`) caused `zimwriterfs` to report and error and fail as follows:
```
root@3090e980e81e:/# zimwriterfs  --uniqueNamespace  -w index.html -f icon.png -l EN -t "Testing Heuristics" -d "Early cut of the testing heuristics material." -c "Julian Harty" -p "Commercetest Ltd." /Volumes/shared/dist/ /Volumes/shared/th-ln.zim

create directory entries
collect articles
zimwriterfs: unable to open file at path: /Volumes/shared/dist/A/style.css
terminate called after throwing an instance of 'int'
Aborted
```
Copying the file and then re-running the identical `zimwriterfs` command worked (I had to delete the soft-link first).
```
rm A/style.css 
cp style.css A/
```

_Copied from original issue: openzim/libzim#16_

**Comment by kelson42** [comment]
_From @julianharty on May 8, 2017 20:26_

Relocated from https://github.com/wikimedia/openzim/issues/9

**Comment by kelson42** [comment]
This is a bug in zimwriterfs, not in the zimlib.

**Comment by kelson42** [comment]
Yes, probably a ZIM redirect could be created in that case.

**Comment by akuendig** [comment]
It would be possible to resolve symlinks using [readlink](https://stackoverflow.com/questions/5525668/how-to-implement-readlink-to-find-the-path), [boost filesystem](https://www.boost.org/doc/libs/1_67_0/libs/filesystem/doc/reference.html#read_symlink), or C++ 17 [filesystem::read_symlink](https://en.cppreference.com/w/cpp/filesystem/read_symlink).

Which of those would be an option?

**Comment by kelson42** [comment]
@akuendig boost is not really an option as we try to avoid new dependencies. readlink or read_symlink seem acceptable to me but I'm not so sure about the relative advantages. readlink seems the most robust (old take) but maybe read_symlink provide other advantages (speed?).

**Comment by akuendig** [comment]
If possible, I would go for read_symlink since that has a stricter API (working with path objects instead of strings) and is standardised.
The only blocker would be compiler support. Looking at the map on [cppreference](https://en.cppreference.com/w/cpp/compiler_support) it looks like only gcc 8 supports it.
Therefore, it might be better to go with readlink and move to read_symlink later.

**Comment by kelson42** [comment]
@akuendig Sad that only gcc8 supports it... but we have to compile or code with many different compilers... So unfortunately that move sounds a bit to bold indeed. Lets go for readlink (but please a comment that we do not forgot about that and implement it properly in 2-3 years. You can also provide the two implementations! ;)

**Comment by mgautierfr** [comment]
I haven't test with zimwriterfs especially. But zimwriterfs use `std::ifstream` to open the file and it resolve correctly (and naturaly) symlink. (ie, if the path is a symlink, `std::ifstream` will open the target) I've tested this.
`std::ifstream` will fail if the symlink is incorrect.

And indeed, `create a soft-link using ln -s for style.css: ln -s style.css A/style.css` is incorrect.
It will create a symlink called `style.css` in directory `A` pointing to `style.css` (so pointing to itself)
It is normal that zimwriterfs cannot open this file.

**Comment by asashnov** [comment]
Reproduced, stacktrace around the fault:
<details>
  <summary>partial stacktrace</summary>
  
  ``` 
#4  0x00007fbf352b1b21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fbf352b1d54 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005604d156594f in getFileContent (path="/home/alex/oz/testing-heuristics/dist/A/style.css")
    at ../src/tools.cpp:202
#7  0x00005604d156d29a in FileArticle::readData (this=0x5604d2e7d5b0) at ../src/article.cpp:70
```
</details>

**Comment by asashnov** [comment]
Another case we should consider- looping symlink
